name: devcontainer

on:
  push:
    branches:
      - "**"
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer.yml"

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v6
      - name: "Test: Build and run dev container"
        uses: devcontainers/ci@v0.3
        with:
          runCmd: dotnet build src
          push: never
